name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Install sqlite
        run: sudo apt-get install libsqlite3-dev
      - uses: actions/checkout@v1
      - name: Set up Ruby 2.5
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.5.x
      - name: Run build
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        run: bash ./generate-github.sh
